name = "smp"
mc_version = "1.20.1"

[jar]
type = "fabric"
loader = "latest"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = true

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "ba99D9Qf"

[[mods]]
type = "modrinth"
id = "lithium"
version = "ZSNsJrPI"

[[mods]]
type = "modrinth"
id = "ferrite-core"
version = "unerR5MN"

[[mods]]
type = "modrinth"
id = "krypton"
version = "jiDwS0W1"

[[mods]]
type = "modrinth"
id = "fabric-language-kotlin"
version = "ZMokinzs"

[[mods]]
type = "modrinth"
id = "create-origins"
version = "2YRyvxvy"

[[mods]]
type = "modrinth"
id = "origins"
version = "OdNHB7Bh"

[[mods]]
type = "modrinth"
id = "estrogen"
version = "Fbz77g1I"

[[mods]]
type = "modrinth"
id = "create-fabric"
version = "A8R3Be5A"

[[mods]]
type = "modrinth"
id = "trinkets"
version = "AHxQGtuC"

[[mods]]
type = "modrinth"
id = "botarium"
version = "5a8eybLl"

[[mods]]
type = "modrinth"
id = "resourceful-lib"
version = "eHrhVCDK"

[[mods]]
type = "modrinth"
id = "jade"
version = "yksHdZ4j"

[[mods]]
type = "modrinth"
id = "jade-addons-fabric"
version = "8NamGveF"

[[mods]]
type = "modrinth"
id = "terralith"
version = "FgvUosFH"

[[mods]]
type = "modrinth"
id = "tectonic"
version = "PFg0zBtc"

[[mods]]
type = "modrinth"
id = "artifacts"
version = "Uetdhalv"

[[mods]]
type = "modrinth"
id = "azurelib"
version = "9e6pFQts"

[[mods]]
type = "modrinth"
id = "badpackets"
version = "JjLWLyDz"

[[mods]]
type = "modrinth"
id = "blahaj"
version = "uLiIwYwS"

[[mods]]
type = "modrinth"
id = "no-chat-reports"
version = "HeZZR2kF"

[[mods]]
type = "modrinth"
id = "pehkui"
version = "czRgm3k6"

[[mods]]
type = "modrinth"
id = "cc-tweaked"
version = "ekffpGYP"

[[mods]]
type = "modrinth"
id = "emi"
version = "ab3hfPOi"

[[mods]]
type = "modrinth"
id = "emitrades"
version = "kWMqVWTm"

[[mods]]
type = "modrinth"
id = "emi-loot"
version = "lwhMjJHL"

[[mods]]
type = "modrinth"
id = "emiffect"
version = "BslzSzGd"

[[mods]]
type = "modrinth"
id = "extra-mod-integrations"
version = "kTtFhI1L"

[[mods]]
type = "modrinth"
id = "fabric-seasons"
version = "uMEzKato"

[[mods]]
type = "modrinth"
id = "fabric-seasons-terralith-compat"
version = "MJ2OF7eg"

[[mods]]
type = "modrinth"
id = "architectury-api"
version = "WbL7MStR"

[[mods]]
type = "modrinth"
id = "image2map"
version = "T71Apams"

[[mods]]
type = "modrinth"
id = "improved-inchling-origin"
version = "CMwBLebQ"

[[mods]]
type = "modrinth"
id = "apugli"
version = "PDYXapHt"

[[mods]]
type = "modrinth"
id = "universal-graves"
version = "KaGNkIdU"

[[mods]]
type = "modrinth"
id = "polymorph"
version = "akZJjqpV"

[[mods]]
type = "modrinth"
id = "slimeorigin"
version = "yQzTujqg"

[[mods]]
type = "modrinth"
id = "origin-furs"
version = "YsNh3WnN"

[[mods]]
type = "modrinth"
id = "carry-on"
version = "Mkla4B3q"

[[mods]]
type = "modrinth"
id = "tree-harvester"
version = "3xpkqLbJ"

[[mods]]
type = "modrinth"
id = "collective"
version = "ENGS2tc8"

[[mods]]
type = "modrinth"
id = "cccbridge"
version = "57pJUQQM"

[[mods]]
type = "modrinth"
id = "polymer"
version = "3ii2xU3x"

[[mods]]
type = "modrinth"
id = "sodium"
version = "mhZtY2lR"

[[mods]]
type = "modrinth"
id = "iris"
version = "KHQ2Hnpt"

[[mods]]
type = "modrinth"
id = "indium"
version = "Aouse6P7"

[[mods]]
type = "modrinth"
id = "sodium-extra"
version = "I7ggF6B5"

[[mods]]
type = "modrinth"
id = "reeses-sodium-options"
version = "Rc9pkPug"

[[mods]]
type = "modrinth"
id = "modmenu"
version = "lEkperf6"

[[mods]]
type = "modrinth"
id = "memoryleakfix"
version = "5xvCCRjJ"

[[mods]]
type = "modrinth"
id = "simple-voice-chat"
version = "es78rsMC"

[[mods]]
type = "modrinth"
id = "no-chat-reports"
version = "HeZZR2kF"

[[mods]]
type = "modrinth"
id = "zoomify"
version = "gZr7EykF"

[[mods]]
type = "modrinth"
id = "debugify"
version = "6XDJoCks"

[[mods]]
type = "modrinth"
id = "better-combat"
version = "jhqZUDtT"

[[mods]]
type = "modrinth"
id = "playeranimator"
version = "yDqYTUaf"

[[mods]]
type = "modrinth"
id = "simply-swords"
version = "r5QBtUE9"

[[mods]]
type = "modrinth"
id = "language-reload"
version = "EbPl4WIQ"

[[mods]]
type = "modrinth"
id = "farmers-delight-refabricated"
version = "5dZdVy3m"

[[mods]]
type = "modrinth"
id = "xaeros-minimap"
version = "C2jbx7JG"

[[mods]]
type = "modrinth"
id = "xaeros-world-map"
version = "GOh0fFoJ"

[[mods]]
type = "modrinth"
id = "voice-chat-interaction"
version = "LX0uNyw4"

[[mods]]
type = "modrinth"
id = "styled-nicknames"
version = "9k8RQJkW"
