name = "smp"
version = "a2599274d457aed4e79055bb9e1ddacb8e3a7b87"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "0f3f91403a2c7f878087916509cff3515891735ee613b5ddc379a2baacf51d4b"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
fabric = "latest"
