name = "smp"
version = "7efbbf8627bd8e15078da7a14806f9133c85b579"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "634e504a566be3247c5c48dce31d32a57713ad023dba1ed8d1834b178c8e0afc"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "latest"
minecraft = "1.20.1"
