name = "smp"
version = "bc2b995902bc73e6aefee1a2066670cec731bec2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "720cf50e101e64ec3b2c40c124a8552c7090933c773f3a6b1dd6bda555ed63fe"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "latest"
minecraft = "1.20.1"
