name = ""
version = "f9071f18e3c41e0efb8952a0441ccd5899d6f9f0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "bf9801ff593411886dd26e78eaba9a0f921eee4a4ac622eac1dd5a8eb5a1742d"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.1"
fabric = "0.15.11"
