name: Update Packwiz and Markdown

on:
  push:
    branches:
      - main
    paths:
      - config/**
      - server.toml
      - .github/workflows/packwiz.yml
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Install mcman
      run: |
        wget https://github.com/ParadigmMC/mcman/releases/latest/download/mcman
        sudo mv ./mcman /usr/bin/
        sudo chmod +x /usr/bin/mcman

    - name: Delete pack/
      run: rm -r ./pack

    - name: Run mcman export packwiz
      run: mcman export packwiz
      env:
        MODPACK_VERSION: ${{ github.sha }}

    - name: Update markdown
      run: mcman markdown

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update packwiz pack and readme
